### PR TITLE
Fixing variable length integer encoding

### LINKED ISSUE #7: Variable length integers encoded incorrectly
Variable length integers appear to be encoded incorrectly.

This can cause messages with lengths larger than 128 to register as malformed packets.

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR fixes #7 by correcting the encoding for variable length integers. The order was previously reversed.

Testing:
* An MQTT publish packet was generated with a size of 386. It was confirmed that the packet was properly digested by the broker.

### CODE REVIEW

File: src/ser/packet_writer.rs [hunk 1]
```diff
@@ -99,23 +99,23 @@ impl<'a> ReversedPacketWriter<'a> {
...
-                (value >> 7) as u8 | 0x80,
                 (value >> 0) as u8 | 0x80,
+                (value >> 7) as u8 | 0x80,
+                (value >> 14) as u8 & 0x7F,
             ];
 
             self.write(&data)
         } else if value & (0b0111_1111 << 7) > 0 {
-            let data: [u8; 2] = [(value >> 7) as u8 & 0x7F, (value >> 0) as u8 | 0x80];
+            let data: [u8; 2] = [(value >> 0) as u8 | 0x80, ((value >> 7) & 0x7F) as u8];
```
Comment (ryan-summers) [inline src/ser/packet_writer.rs:118]: Let's add unit tests for this.
