### PR TITLE
fix ping

### LINKED ISSUE #186: Omit unnecessary keep alive ping
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#:~:text=maximum%20time%20interval

> The Keep Alive is a Two Byte Integer which is a time interval measured in seconds. It is the maximum time interval that is permitted to elapse between the point at which the Client finishes transmitting one MQTT Control Packet and the point it starts sending the next. It is the responsibility of the Client to ensure that the interval between MQTT Control Packets being sent does not exceed the Keep Alive value. If Keep Alive is non-zero and in the absence of sending any other MQTT Control Packets, the Client MUST send a PINGREQ packet.

Other implements:

[eclipse/paho](github.com/eclipse-paho/paho.mqtt.c) do these well, in it's MQTTProtocolClient.c:

https://github.com/eclipse-paho/paho.mqtt.c/blob/v1.3.16/src/MQTTProtocolClient.c#L748-L752

Only send PINGREQ when `difftime(now, client->net.lastSent) >= client->keepAliveInterval`, and, send any packet successfully will update `lastSent`.

@jordens  Seems that you're doing a big refactor, my PR got outdated, hope this feature to be considered.

### PR DESCRIPTION
**Pull request by jordens**
- **fix ping timeout updates**
- **outbound: extract common path**

### CODE REVIEW

**Review by kkocdko — APPROVED** [review]
I took a careful look, and it looks wonderful, thanks!

File: src/mqtt_client/core.rs [hunk 1]
```diff
@@ -815,20 +817,11 @@ impl<'buf> Core<'buf> {
...
-                    {
-                        Ok(count) => count,
-                        Err(err) => {
-                            self.handle_disconnect();
-                            return Err(err);
-                        }
-                    };
+                    let count = self.disconnect_on_error({
+                        let packet = self.session.outbound.retained_packet(step.offset, step.len);
+                        Self::write_step_bytes(connection, "Retained packet", &packet[written..])
```
Comment (kkocdko) [inline src/mqtt_client/core.rs]: I found that the `log::log!("content")` will be optimized in release build, but function call with static string will not, like `Self::write_step_bytes(connection, "Retained packet", xxx)`.

```
kkocdko@klp1:~/misc/code/kmbed/aio-esp32c3$ cat target/riscv32imc-unknown-none-elf/release/aio-esp32c3 | grep --binary "Flushing PUBREL packet packet_id"
kkocdko@klp1:~/misc/code/kmbed/aio-esp32c3$ 
kkocdko@klp1:~/misc/code/kmbed/aio-esp32c3$ cat target/riscv32imc-unknown-none-elf/release/aio-esp32c3 | grep --binary "Retained packet"
grep: (standard input): binary file matches
kkocdko@klp1:~/misc/code/kmbed/aio-esp32c3$ 
```

However, may not a big problem.

Comment (jordens) [reply src/mqtt_client/core.rs]: Oh yeah. That's bad.

**Review by kkocdko — APPROVED** [review]
