### PR TITLE
Fixing MQTT permanent disconnection issues

### LINKED ISSUE #125: Multiple socket disconnections may cause the client to fail to reconnect
If the TCP socket connection is lost immediately after the socket is opened, but before the `Connect` packet can be sent, the state machine gets stuck in a way that means that the MQTT client will never reconnect to the broker.

The only method to force a reconnection would be a forced power cycle of the device.

Identified in https://github.com/quartiq/stabilizer/issues/674

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR fixes #125 

TODO:
- [x] Update `std-embedded-nal` + integration tests
- [x] Wait for https://github.com/rust-embedded-community/embedded-nal/pull/85 to release

### CODE REVIEW

File: src/mqtt_client.rs [hunk 1]
```diff
@@ -438,21 +435,21 @@ impl<
     }
 
     fn update(&mut self) -> Result<(), Error<TcpStack::Error>> {
-        // Potentially update the state machine depending on the current socket connection status.
-        let tcp_connected = self.network.tcp_connected()?;
-
-        if !tcp_connected {
-            self.sm.process_event(Events::TcpDisconnect).ok();
+        if self.network.socket_was_closed() {
+            warn!("Handling closed socket");
```
Comment (jordens) [inline src/mqtt_client.rs:439]: I'd leave this at info. Disconnects are normal operation.

**Review by jordens — APPROVED** [review]
