### PR TITLE
Handling partial MQTT packet writes

### LINKED ISSUE #74: Partially transmitted packets cause broker disconnection
As pointed out in https://github.com/quartiq/minimq/pull/68, any partial packet write ultimately results in a broker disconnection because the broker fails to receive a complete MQTT packet.

Currently, there's no mechanism to check and see if a packet can be entirely written before we write it, so we likely need to do the following:
* Buffer any yet-to-be-written packet data
* Provide an API to check to see if Minimq can send a packet (e.g. the buffer is not in use)

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR fixes #74 by incorporating changes from #68 with additional safeguards.

Specifically, any attempt to write a packet is now safe guarded by checking that packet writes are acceptable. It's invalid to attempt to send a packet while a partial packet is still being transmitted, as this would corrupt the MQTT connection.

CC @mladedav

### CODE REVIEW

File: src/network_manager.rs [hunk 1]
```diff
@@ -24,9 +26,15 @@ where
         Self {
             socket: None,
             network_stack: stack,
+            unfinished_packet: None,
```
Comment (jordens) [inline src/network_manager.rs:29]: `pending_write`? It's not a packet.

File: src/network_manager.rs [hunk 2]
```diff
@@ -79,6 +91,9 @@ where
     /// # Args
     /// * `packet` - The packet to write.
     pub fn write(&mut self, packet: &[u8]) -> Result<(), Error<TcpStack::Error>> {
```
Comment (jordens) [inline src/network_manager.rs:93]: `message` (as used for the same thing in other places) or `data` would be better since there is no guaranteed correlation with (Ethernet/TCP) packets.

**Review by jordens — CHANGES_REQUESTED** [review]

**Review by jordens — APPROVED** [review]

**Comment by ryan-summers** [comment]
@mladedav Thanks for pointing out the other issue. I've added it to the issue tracker and submitted a PR.

In the future, I'd recommend posting things like this as an issue - I nearly missed this comment
